### ISSUE TITLE
Contrast issue with light theme

### ISSUE THREAD

**Issue by borisrorsvort** [AstroNvim/astrotheme#76]
First of all let me applause the huge work you’ve done on the theme 👏  I love the default one ❤️  
But I’ve been on a quest to find a decent light theme and I was hoping to find the same quality in the light version, but I find that the colours accessibility, specially text contrast, is way lower than the dark themes. 
I know some themes have high contrast versions but I'm not requesting that here, merely to make it coherent with the default dark contrast levels. 
I know we can all customise it, but I found that the default experience would benefit from a more coherent approach.

**Comment by A-Lamia** [comment]
Hey thanks for the kind words and feed back, astrolight and mars are both getting a revisit soon as they need some better tuning, as for contrast though astrolight actually has the best contrast ratio out of all 3 of the themes is there somethings specific that is bothering you or you are wanting that you can't find ?

As some one who does not like light themes it would be nice to have some feed back on what you are looking for :)

**Comment by borisrorsvort** [comment]
@A-Lamia  I’m very surprised you say that astrolight has the best contrast ratio. Looking at this screenshot. The dark theme is so much more readable. 
<img width="1792" alt="Capture d’écran 2023-07-23 à 22 19 04" src="https://github.com/AstroNvim/astrotheme/assets/39081/daa9ee1d-313d-4b4b-b0cf-b31428945884">


The best light theme I know is the one from GitHub. https://github.com/callstack/linaria/blob/520ba8da095dd879bb694ced1d9d388a3a8ac1ee/packages/shaker/src/plugins/shaker-plugin.ts

But even the nvim GitHub theme project seem to not be a able to make it identical.

**Comment by A-Lamia** [comment]
@borisrorsvort did you perhaps send me a wrong link ? 

And my comment on it having better contrast is based on a contrast algorithm for checking the perceptual contrast level between the background and text. 😀 I asked for an example because the issue may not be contrast but something else like chroma.

**Comment by A-Lamia** [comment]
Ok I think I understand what I'm looking it, this is a maximum contrast type of theme, it's the equivalent of having astro dark set to `#000000`.

By default dark themes will seem to have more contrast even at lower perceptual levels because the text it self is the brightest point.

I'll look at exploring a high contrast light theme 😀
