### ISSUE TITLE
No Highlight colors?

### ISSUE THREAD

**Issue by cjauton** [AstroNvim/astrotheme#81]
It appears that the highlight colors have been removed. Why is this?
<img width="570" alt="Screenshot 2023-08-07 at 12 56 18 AM" src="https://github.com/AstroNvim/astrotheme/assets/126740758/6db9e0d5-7ad7-44eb-af77-30b8c0235d15">
<img width="209" alt="Screenshot 2023-08-07 at 12 55 15 AM" src="https://github.com/AstroNvim/astrotheme/assets/126740758/15412e06-bf4c-44b1-b0a8-d1f1fe19fe00">

**Comment by A-Lamia** [comment]
Yes for now I've changed it to have no highlights until i figure out how i want o handle them with light / dark themes, didn't think it was a big deal there seems to be a lot of popular themes with no highlights and I've been using it with no issue, is there something specific that this is breaking ?

**Comment by cjauton** [comment]
I see. I don't think its a big deal for now. I know some popular CLI tools like `exa` make use of the bright versions of distinguishing file types.

**Comment by A-Lamia** [comment]
ah ok, well this should be resolved sooner then later just have some more important things to take care of then ill be taking a look at terminal :)

**Comment by Hacksore** [comment]
Since we discussed this on discord figured I'd share it here for others looking for anwsers. No highlight colors means prettier can't render gray when a file is unchanged and instead renders as black.

![image](https://github.com/AstroNvim/astrotheme/assets/996134/bbb6a75d-fc37-45f7-be0c-6880281c9ef1)

discord thread: https://discord.com/channels/939594913560031363/1215651848200134666

**Comment by Hacksore** [comment]
The workaround for prettier, as suggested by @A-Lamia, is just hard code the offending color 😅.

```lua
return {
  "astronvim/astrotheme",
  opts = {
    palettes = {
      astrodark = {
        term = {
          bright_black = "#767676",
        }
      },
    },
  }
}
```
